version: "3"
services:
    code-server:
        build: ./code-server
        container_name: code-server
        restart: always
        environment:
            PASSWORD: xxxxx 
            GIT_USERNAME: username
            GIT_EMAIL: email
        ports:
            - "20010:8443"
            - "20011:4000"
        volumes:
            - project:/home/coder/project:rw
            - extension:/home/coder/extension:rw
            - user-data:/home/coder/user-data:rw
            - ssh:/home/coder/.ssh:rw

volumes:
    project:
    extension:
    user-data:
    ssh:
